FROM pecan/model-sipnet-git
# ----------------------------------------------------------------------
# ADD IN TARGETS FOR CCMMF NEEDS
# ----------------------------------------------------------------------

RUN Rscript --vanilla -e "install.packages(c('targets', 'uuid', 'tarchetypes'), repos = c(CRAN = 'cloud.r-project.org'))"
