# Tutorials {#user-section}

PEcAn provides an interface to a variety of ecosystem models and attempts to standardize and automate the processes of model parameterization, execution, and analysis. First, you choose an ecosystem model, then the time and location of interest (a site), the plant community (or crop) that you are interested in simulating, and a source of atmospheric data from the BETY database (LeBauer et al, 2010). These are set in a "settings" file, commonly named `pecan.xml` which can be edited manually if desired. From here, PEcAn will take over and set up and execute the selected model using your settings. The key is that PEcAn uses models as-is, and all of the translation steps are done within PEcAn so no modifications are required of the model itself. Once the model is finished it will allow you to create graphs with the results of the simulation as well as download the results. It is also possible to see all past experiments and simulations.

There are two ways of using PEcAn, via the web interface and directly within R. Even for users familiar with R, using the web interface is a good place to start because it provides a high level overview of the PEcAn workflow. The quickest way to get started is to download the virtual machine or use an AWS instance.

The following Tutorials assume you have installed PEcAn. If you have not, please consult the [PEcAn Installation Section](#pecan-manual-setup).

|Type|Title|Web Link| Source Rmd|
|:--:|:---:|:------:|:---------:|
|Demo| Basic Run| [html](#demo-1) | <a href="https://github.com/PecanProject/pecan/blob/develop/documentation/tutorials/01_Demo_Basic_Run/Demo01.Rmd" target = "_blank">Rmd</a> |
|Demo| Uncertainty Analysis| [html](#demo-2)| <a href="https://github.com/PecanProject/pecan/blob/develop/documentation/tutorials/02_Demo_Uncertainty_Analysis/Demo02.Rmd" target = "_blank">Rmd</a> |
|Demo| Output Analysis|html | <a href="https://github.com/PecanProject/pecan/blob/develop/documentation/tutorials/AnalyzeOutput/modelVSdata.Rmd" target="_blank">Rmd</a> |
|Demo| MCMC |html| <a href= "https://github.com/PecanProject/pecan/blob/develop/documentation/tutorials/MCMC/MCMC_Concepts.Rmd" target = "_blank">Rmd</a> |
|Demo|Parameter Assimilation |html | <a href="https://github.com/PecanProject/pecan/blob/develop/documentation/tutorials/ParameterAssimilation/PDA.Rmd" target = "_blank">Rmd</a> |
|Demo|State Assimilation|html| <a href="https://github.com/PecanProject/pecan/blob/develop/documentation/tutorials/StateAssimilation/TreeRingSDA.Rmd" target = "_blank">Rmd</a> |
|Demo| Sensitivity|html| <a href="https://github.com/PecanProject/pecan/blob/develop/documentation/tutorials/sensitivity/PEcAn_sensitivity_tutorial_v1.0.Rmd" target = "_blank">Rmd</a> |
|Vignette|Allometries|html| <a href="https://github.com/PecanProject/pecan/blob/develop/modules/allometry/vignettes/AllomVignette.Rmd" target = "_blank">Rmd</a> |
|Vignette|MCMC|html| <a href="https://github.com/PecanProject/pecan/blob/develop/modules/assim.batch/vignettes/AssimBatchVignette.Rmd" target = "_blank">Rmd</a> |
|Vignette|Meteorological Data|html| <a href="https://github.com/PecanProject/pecan/tree/develop/modules/data.atmosphere/vignettes" target = "_blank">Rmd</a> |
|Vignette|Meta-Analysis|html| <a href="https://github.com/PecanProject/pecan/blob/develop/modules/meta.analysis/vignettes/single.MA_demo.Rmd" target = "_blank">Rmd</a> |
|Vignette|Photosynthetic Response Curves|html| <a href="https://github.com/PecanProject/pecan/blob/develop/modules/photosynthesis/vignettes/ResponseCurves.Rmd" target = "_blank">Rmd</a> |
|Vignette|Priors|html| <a href="https://github.com/PecanProject/pecan/blob/develop/modules/priors/vignettes/priors_demo.Rmd" target = "_blank">Rmd</a> |
|Vignette|Leaf Spectra:PROSPECT inversion|html| <a href="https://github.com/PecanProject/pecan/blob/develop/modules/rtm/vignettes/pecanrtm.vignette.Rmd" target = "_blank">Rmd</a> |